name: Terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'

      - name: Install Terratest dependencies
        run: |
          cd test
          go mod init terratest
          go get -v github.com/gruntwork-io/terratest/modules/terraform
          go get -v github.com/stretchr/testify
          go get -v github.com/gruntwork-io/terratest/modules/http-helper

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.0.11

      - name: Terraform Init and Apply
        working-directory: ./
        run: terraform init && terraform apply -auto-approve

      - name: Run Terratest
        working-directory: ./test
        run: go test -v -timeout 30m

      - name: Terraform Destroy
        if: always()
        working-directory: ./
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
