name: Terratest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terratest:
    runs-on: ubuntu-latest
    environment: AWS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18'
    
      - name: Cache Go modules
        uses: actions/cache@v2
        with:
          path: /path/to/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/*.go') }}
          restore-keys: |
            ${{ runner.os }}-go-
    
      - name: Install dependencies
        run: |
          go mod init test || true  # This avoids failure if the module is already initialized
          go mod tidy
    
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
    
      - name: Terraform Init
        run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Run Terratest
        working-directory: ./test  # Adjust this path if your tests are located elsewhere
        run: go test -v
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}