name: Terraform Provisioning

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0  # Replace this with the desired version if needed

    - name: Initialize Terraform
      working-directory: ./terraform  # Make sure this points to your Terraform directory
      run: terraform init

    - name: Plan Terraform Changes
      working-directory: ./terraform
      run: terraform plan

    - name: Apply Terraform Changes
      if: github.ref == 'refs/heads/main'
      working-directory: ./terraform
      run: terraform apply -auto-approve
